version: '3'

services:
  db:
    image: postgres:12.5-alpine
    container_name: confluence_db
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - proxy-tier


  app:
    image: atlassian/confluence-server:latest
    container_name: confluence_app
    restart: unless-stopped
    volumes:
      - data:/var/atlassian/application-data/confluence
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8090:8090
    env_file:
      - app.env
    depends_on:
      - db
    networks:
      - proxy-tier

  proxy:
    build: ./proxy
    container_name: confluence_proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - proxy-tier


  backup:
    build: ./backup
    container_name: confluence_backup
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=confluence_db
    env_file:
      - db.env
      - backup.env
    volumes:
      - data:/data/confluence/data
      - backup:/backup/confluence
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    tty: true
    networks:
      - proxy-tier
    depends_on:
      - db
      - app

volumes:
  db:
    driver_opts:
      type: none
      device: /data/confluence/db
      o: bind
  data:
    driver_opts:
      type: none
      device: /data/confluence/data
      o: bind
  backup:
    driver_opts:
      type: none
      device: /backup/confluence
      o: bind
  certs:
  vhost.d:
  html:
  acme:

networks:
  proxy-tier:
